version: '3'
services:
    web:
        image: nginx:1.15.6 #pullするimage
        ports:
            - "8000:80" # (host):(server)ポート接続
        volumes: #フォルダと設定ファイルのマウント
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html