version: '3'
services:
    web:
        image: nginx:1.15.6 #pullするimage
        ports:
            - "8000:80" # (host):(server)ポート接続
        depends_on: #依存関係を定義するオプション
            - app
        volumes: #フォルダと設定ファイルのマウント
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    app:
        build: ./docker/php # 定義したDockerfileを元にイメージを作る
        depends_on: 
            - mysql
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data: